-- 입양을 간 동물 중,
-- 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름을 조회
-- 결과는 보호 기간이 긴 순으로 조회
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS
INNER JOIN ANIMAL_OUTS OUTS ON OUTS.ANIMAL_ID LIKE INS.ANIMAL_ID
GROUP BY DATEDIFF(INS.DATETIME, OUTS.DATETIME)
ORDER BY DATEDIFF(INS.DATETIME, OUTS.DATETIME) LIMIT 2
