-- 코드를 입력하세요
SELECT 
    UGU.USER_ID, 
    UGU.NICKNAME, 
    CONCAT(UGU.CITY," ",UGU.STREET_ADDRESS1," ",UGU.STREET_ADDRESS2) AS "전체주소",
    # REGEXP_REPLACE(UGU.TLNO,'(02|.{3})(.+)(.{4})', '\\1-\\2-\\3') AS "전화번호"
    CONCAT(
        SUBSTRING(UGU.TLNO FROM 1 FOR 3), "-",
        SUBSTRING(UGU.TLNO FROM 4 FOR 4), "-",
        SUBSTRING(UGU.TLNO FROM 8 FOR 4)
    ) AS "전화번호"
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY UGU.USER_ID
HAVING COUNT(UGB.WRITER_ID)>2
ORDER BY UGU.USER_ID DESC