-- USED_GOODS_BOARD와 USED_GOODS_USER 테이블에서 
-- 완료된 중고 거래의 총금액이 70만 원 이상인 사람의
-- 회원 ID, 닉네임, 총거래금액을 조회
-- 결과는 총거래금액을 기준으로 오름차순 정렬
# SELECT UGU.USER_ID, UGU.NICKNAME, UGB.TOTAL_SALES
# FROM USED_GOODS_USER UGU
# INNER JOIN (
#     SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
#     FROM USED_GOODS_BOARD
#     WHERE "STATUS" LIKE "DONE"
#     GROUP BY WRITER_ID
#     HAVING SUM(PRICE) >= 700000    
#     ) UGB ON UGU.USER_ID = UGB.WRITER_ID
# ORDER BY TOTAL_SALES ASC

SELECT 
    UGU.USER_ID,
    UGU.NICKNAME,
    SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.STATUS LIKE "DONE"
GROUP BY UGU.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC